version: '3'

vars:
  CSS_INPUT: ./resources/css/styles.css
  CSS_OUTPUT: ./public/css/styles.css
  SERVER_PORT: 3000
  ENTRYPOINT: ./cmd/app/app.go

tasks:
  setup:
    cmds:
      - bash ./scripts/tools.sh

  'css:dev':
    cmds: 
      - tailwindcss -i {{.CSS_INPUT}} -o {{.CSS_OUTPUT}} --watch

  'css:build':
    cmds:
      - tailwindcss -i {{.CSS_INPUT}} -o {{.CSS_OUTPUT}} --minify

  'server:dev':
    cmds:
      - templ generate --watch --proxy="http://localhost:{{.SERVER_PORT}}" --open-browser=false --cmd="go run {{.ENTRYPOINT}}"

  'server:build':
    cmds:
      - templ generate

  build:
    cmds:
      - task: css:build
      - task: server:build
      - go build {{.ENTRYPOINT}}
      - rm -rf ./dist
      - mkdir -p ./dist
      - mv -v ./app ./dist
      - cp -r ./public ./dist